spring:
    datasource:
        # 使用基于内存地数据库
        platform: h2
    #JPA配置
    jpa:
        database: MySQL
        show-sql: true
        hibernate:
            ddl-auto: create
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                format_sql: true
    #设置编码格式
    http:
        encoding:
            force: true
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    mvc:
        # Path pattern used for static resources,TODO
        static-path-pattern: /**
    # 静态资源根路径(可以存放网站图标)
    resources:
        static-locations: classpath:/static/
    velocity:
        resource-loader-path: classpath:/velocity/
#web容器的端口号和编码配置
server:
    #修改Tomcat端口号,默认端口号8080
    port: 8086
management:
    port: 9001
lx:
    # 定义数组
    favorite:
        numbers: 6,8,10
    # 获取uuid
    uuid:
        ${random.uuid}
    # 获取范围内int
    number:
        in:
            range: ${random.int[10,20]}
    # 配置属性列表,等同于lx.websites=www.liangxiong.com,www.liangxiong.cn
    websites:
        -  www.liangxiong.cn
        -  www.liangxiong.com
# Spring Boot uses some relaxed rules for binding Environment properties to @ConfigurationProperties beans, so there doesn’t need to be an exact match between the Environment property name and the bean property name
bar:
    first-name: tomcat
logging:
    config: classpath:log/logback-spring.xml
# logback-spring.xml中springProperty需要
user: liangxiong
# security相关配置
security:
    user:
        # 登录账号
        name: admin
        # 登陆密码
        password: 123456
    oauth2:
        client:
            client-id: liangxiong
            client-secret: 111111