spring:
    datasource:
        # 使用基于内存地数据库
        platform: h2
    #JPA配置
    jpa:
        # 数据库方言
        databasePlatform: org.hibernate.dialect.MySQL5Dialect
        # 数据库名称
        database: MYSQL
        # 控制台打印SQL语句
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                implicitStrategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                format_sql: true
    #设置编码格式
    http:
        encoding:
            force: true
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    mvc:
        # Path pattern used for static resources,TODO
        static-path-pattern: /**
    # 静态资源根路径(可以存放网站图标)
    resources:
        static-locations: classpath:/static/
    velocity:
        resource-loader-path: classpath:/velocity/
#web容器的端口号和编码配置
server:
    #修改Tomcat端口号,默认端口号8080
    port: 8086
management:
    port: 9001
lx:
    # 定义数组
    favorite:
        numbers: 6,8,10
    # 获取uuid
    uuid:
        ${random.uuid}
    # 获取范围内int
    number:
        in:
            range: ${random.int[10,20]}
    # 配置属性列表,等同于lx.websites=www.liangxiong.com,www.liangxiong.cn
    websites:
        -  www.liangxiong.cn
        -  www.liangxiong.com
# Spring Boot uses some relaxed rules for binding Environment properties to @ConfigurationProperties beans, so there doesn’t need to be an exact match between the Environment property name and the bean property name
bar:
    first-name: tomcat
logging:
    config: classpath:log/logback-spring.xml
# logback-spring.xml中springProperty需要
user: liangxiong
# security相关配置
security:
    user:
        # 登录账号
        name: admin
        # 登陆密码
        password: 123456
    oauth2:
        client:
            client-id: liangxiong
            client-secret: 111111
    # 关闭Spring Security安全认证
    basic:
        enabled: false
# MyBatis相关配置
mybatis:
    # Locations of MyBatis mappers files.
    mapper-locations: classpath:mappers/*.xml
    # 是否检查配置的XML文件
    check-config-location: true
    # 配置别名
    type-aliases-package: org.liangxiong.springboot.entity
    # 配置Java属性和数据库字段驼峰命名映射(针对Annotation和XML都有效)
    configuration:
        map-underscore-to-camel-case: true
pagehelper:
    # 5.0的为helperDialect;老版本为dialect
    helperDialect: MySQL
    # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页;禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
    reasonable: true
    # 支持通过Mapper接口参数来传递分页参数
    supportMethodsArguments: true
    params: count=countSql
    autoRuntimeDialect: true
    # 设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果
    pageSizeZero: true
    # 设置为true时，会将RowBounds第一个参数offset当成pageNum页码使用
    offsetAsPageNum: true
    # 当该参数设置为true时，使用RowBounds分页会进行count查询
    rowBoundsWithCount: true