spring:
    #数据库配置信息
    datasource:
        # 引入druid
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: admin
        #druid连接池配置
        #最大活跃数
        maxActive: 20
        #初始化连接数量
        initialSize: 5
        #连接最大超时时间
        maxWait: 60000
        #打开PSCache,并且指定每个连接PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #通过connectionProperties属性来打开mergeSql功能;慢SQL记录
        #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select '1' from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
        filters: stat, wall, log4j
    #JPA配置
    jpa:
        # 数据库方言
        databasePlatform: org.hibernate.dialect.MySQL5Dialect
        # 数据库名称
        database: MYSQL
        # 控制台打印SQL语句
        show-sql: true
        hibernate:
            ddl-auto: create
            naming:
                implicitStrategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                format_sql: true
    #设置编码格式
    http:
        encoding:
            force: true
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    mvc:
        view:
            # 视图访问路径前缀
            prefix: /WEB-INF/jsp/
            # 视图访问路径后缀
            suffix: .jsp
        # Path pattern used for static resources,TODO
        static-path-pattern: /**
    # 静态资源根路径(可以存放网站图标)
    resources:
        static-locations: classpath:/static/
    velocity:
        resource-loader-path: classpath:/velocity/
#web容器的端口号和编码配置
server:
    #修改Tomcat端口号,默认端口号8080
    port: 8086
management:
    port: 9001
lx:
    # 定义数组
    favorite:
        numbers: 6,8,10
    # 获取uuid
    uuid:
        ${random.uuid}
    # 获取范围内int
    number:
        in:
            range: ${random.int[10,20]}
    # 配置属性列表,等同于lx.websites=www.liangxiong.com,www.liangxiong.cn
    websites:
        -  www.liangxiong.cn
        -  www.liangxiong.com
# Spring Boot uses some relaxed rules for binding Environment properties to @ConfigurationProperties beans, so there doesn’t need to be an exact match between the Environment property name and the bean property name
bar:
    first-name: tomcat
logging:
    config: classpath:log/logback-spring.xml
# logback-spring.xml中springProperty需要
user: liangxiong
# security相关配置
security:
    user:
        # 登录账号
        name: admin
        # 登陆密码
        password: 123456
    oauth2:
        client:
            client-id: liangxiong
            client-secret: 111111
# actuator配置优雅停机
endpoints:
    shutdown:
        enabled: true
# MyBatis相关配置
mybatis:
    # Locations of MyBatis mappers files.
    mapper-locations: classpath:mappers/*.xml
    # 是否检查配置的XML文件
    check-config-location: true
    # 配置别名
    type-aliases-package: org.liangxiong.springboot.entity
    # 配置Java属性和数据库字段驼峰命名映射(针对Annotation和XML都有效)
    configuration:
        map-underscore-to-camel-case: true

